kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vsphere-csi-webhook-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: vsphere-csi-webhook
    namespace: vmware-system-csi
roleRef:
  kind: ClusterRole
  name: vsphere-csi-webhook-cluster-role
  apiGroup: rbac.authorization.k8s.io

