apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-validation-deployment
  namespace: kube-system
  labels:
    app: snapshot-validation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snapshot-validation
  template:
    metadata:
      labels:
        app: snapshot-validation
    spec:
      containers:
        - name: snapshot-validation
          image: k8s.gcr.io/sig-storage/snapshot-validation-webhook:v5.0.1 # change the image if you wish to use your own custom validation server image
          imagePullPolicy: IfNotPresent
          args: ['--tls-cert-file=/run/secrets/tls/tls.crt', '--tls-private-key-file=/run/secrets/tls/tls.key']
          ports:
            - containerPort: 443 # change the port as needed
          volumeMounts:
            - name: webhook-certs
              mountPath: /run/secrets/tls
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:

